"""db migration2

Revision ID: 16a83652e8af
Revises: 9982b17441bf
Create Date: 2019-03-07 08:55:54.123933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a83652e8af'
down_revision = '9982b17441bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisors', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('advertisors', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisors', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('advertisors', 'username')
    # ### end Alembic commands ###
