"""Initial Migration

Revision ID: 6ae9d92826ba
Revises: 9b3d41ec1925
Create Date: 2019-03-07 12:01:53.548960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae9d92826ba'
down_revision = '9b3d41ec1925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisors', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('advertisors', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisors', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('advertisors', 'username')
    # ### end Alembic commands ###
