"""Initial Migration

Revision ID: 78f8db88524c
Revises: 6ae9d92826ba
Create Date: 2019-03-07 18:54:16.293930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f8db88524c'
down_revision = '6ae9d92826ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('adverts', sa.Column('location', sa.String(), nullable=True))
    op.add_column('adverts', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'photo')
    op.drop_column('adverts', 'location')
    op.drop_column('adverts', 'description')
    # ### end Alembic commands ###
